# docker-compose.yml
version: '3'
services:
  db:
    image: mysql:latest
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 7777
      MYSQL_DATABASE: blog1_production
      MYSQL_USER: blog1_user
      MYSQL_PASSWORD: 1111
    ports:
      - "3307:3306"
    restart: always

  web:
    build: ./
    depends_on:
      - db
    ports:
      - "3001:3000"
    volumes:
      - .:/blog1
    environment:
      RAILS_ENV: production
      DB_HOST: db
      DB_USERNAME: blog1_user
      DB_PASSWORD: 1111
      DB_NAME_PROD: blog1_production
    restart: always

volumes:
   mysql-data:
