# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: userDB
  password: 7777
  socket: /var/run/mysqld/mysqld.sock
  host: localhost

development:
  <<: *default
  database: blogdb_development

test:
  <<: *default
  database: blog_test

production:
  <<: *default
  database: blogdb_production
  username: userDB
  password: 7777
  host: localhost

